export const trainerActionEnums = {
  GET_TRAINING_CONTENT_REQUEST_COMPLETED: 'GET_TRAINING_CONTENT_REQUEST_COMPLETED',
  INITIALIZE_EDITOR: 'INITIALIZE_EDITOR',
  TRAINING_CONTENT_CHANGED: 'TRAINING_CONTENT_CHANGED',
  UPDATE_EDITOR: 'UPDATE_EDITOR',
};
