const prefix = 'TRAINING_MODULE';

export const trainerActionEnums = {
  GET_TRAINING_CONTENT_REQUEST_COMPLETED: `${prefix}/GET_TRAINING_CONTENT_REQUEST_COMPLETED`,
  TRAINING_CONTENT_CHANGED: `${prefix}/TRAINING_CONTENT_CHANGED`,
  UPDATE_EDITOR_CURSOR: `${prefix}/UPDATE_EDITOR_CURSOR`,
  TOGGLE_EDITOR_PREVIEW: `${prefix}/TOGGLE_EDITOR_PREVIEW`,
};
