
export const adminActionEnums =  {
  GET_SUMMARY_STUDENT_REQUEST_COMPLETED: 'GET_SUMMARY_STUDENT_REQUEST_COMPLETED',
  GET_TRAINING_REQUEST_COMPLETED: 'GET_TRAINING_REQUEST_COMPLETED',
  GET_TRAINING_REQUEST_STARTED: 'GET_TRAINING_REQUEST_STARTED',
}
