
export const adminActionEnums =  {
  GET_SUMMARY_STUDENT_REQUEST_COMPLETED: 'GET_SUMMARY_STUDENT_REQUEST_COMPLETED',
<<<<<<< HEAD
  GET_TRAINING_REQUEST_COMPLETED: 'GET_TRAINING_REQUEST_COMPLETED'
=======
  GET_SUMMARY_TRAINING_REQUEST_COMPLETED: 'GET_SUMMARY_TRAINING_REQUEST_COMPLETED'
>>>>>>> 5541906c0f761bfd48de9d0580e7dcda3a3d4650
}
