export const iconEnums = {
  bold: 'fa fa-bold',
  bulletedList: 'fa fa-list',
  code: 'fa fa-code',
  delivery: 'fa fa-file-archive-o',
  evaluation: 'fa fa-graduation-cap',
  header: 'fa fa-header',
  image: 'fa fa-picture-o',
  italic: 'fa fa-italic',
  link: 'fa fa-link',
  numberedList: 'fa fa-list-ol',
  preview: 'fa fa-eye',
  quote: 'fa fa-quote-right',
  upload: 'fa fa-cloud-upload',
};
