const prefix = 'STUDENT_MODULE';
export const studentActionEnums = {
  FETCH_TRAINING_TOC_COMPLETED: `${prefix}/FETCH_TRAINING_TOC_COMPLETED`,
  GET_SUMMARY_TRAINING_REQUEST_COMPLETED: `${prefix}/GET_SUMMARY_TRAINING_REQUEST_COMPLETED`,
};
