import { Student } from '../model/student';

export const studentMockData: Student[] = [
  {
    email: 'ma_ca@lemoncode.net',
    fullname: 'Mariasha Cameron',
    id: 66,
    isActive: false,
    phoneNumber: '',
  },
  {
    email: 'tiega.straw@lemoncode.net',
    fullname: 'Tiegan Straw',
    id: 62,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'ru_wamsl@lemoncode.net',
    fullname: 'Ruby Wamsley',
    id: 6,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'manjaritru@lemoncode.net',
    fullname: 'Manjari Trusty',
    id: 9,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'amalsessom@lemoncode.net',
    fullname: 'Amalia Sessoms',
    id: 92,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'tam.nevels@lemoncode.net',
    fullname: 'Tammy Nevels',
    id: 47,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'ro_hinso@lemoncode.net',
    fullname: 'Rosa Hinson',
    id: 54,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'amazo_ha@lemoncode.net',
    fullname: 'Amazonia Harada',
    id: 68,
    isActive: false,
    phoneNumber: '',
  },
  {
    email: 'wol-red@lemoncode.net',
    fullname: 'Wolfram Redfern',
    id: 11,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'marderoser@lemoncode.net',
    fullname: 'Marden Roser',
    id: 22,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'micki.jame@lemoncode.net',
    fullname: 'Micki Jamerson',
    id: 8,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'tesi-gastelu@lemoncode.net',
    fullname: 'Tesia Gastelum',
    id: 29,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'tom.cl@lemoncode.net',
    fullname: 'Tomo Class',
    id: 74,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'te.brinson@lemoncode.net',
    fullname: 'Tesia Brinson',
    id: 26,
    isActive: false,
    phoneNumber: '',
  },
  {
    email: 'vivi-cameron@lemoncode.net',
    fullname: 'Vivienne Cameron',
    id: 25,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'huba.co@lemoncode.net',
    fullname: 'Huba Cothran',
    id: 35,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'aja.meza@lemoncode.net',
    fullname: 'Ajay Meza',
    id: 59,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'branchflipp@lemoncode.net',
    fullname: 'Branch Flippen',
    id: 24,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'sign-he@lemoncode.net',
    fullname: 'Signild Herr',
    id: 41,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'leol.ki@lemoncode.net',
    fullname: 'Leola Kiernan',
    id: 36,
    isActive: false,
    phoneNumber: '',
  },
  {
    email: 'er.woodb@lemoncode.net',
    fullname: 'Erma Woodbury',
    id: 86,
    isActive: false,
    phoneNumber: '',
  },
  {
    email: 'melchiorzamarron@lemoncode.net',
    fullname: 'Melchior Zamarron',
    id: 2,
    isActive: false,
    phoneNumber: '',
  },
  {
    email: 'manja.rom@lemoncode.net',
    fullname: 'Manjari Roma',
    id: 61,
    isActive: false,
    phoneNumber: '',
  },
  {
    email: 'qui-gros@lemoncode.net',
    fullname: 'Quintina Grosso',
    id: 28,
    isActive: false,
    phoneNumber: '',
  },
  {
    email: 'suffie.ki@lemoncode.net',
    fullname: 'Suffield Kiernan',
    id: 83,
    isActive: true,
    phoneNumber: '',
  },
  {
    email: 'student@lemoncode.net',
    fullname: 'Student',
    id: 3,
    isActive: true,
    phoneNumber: '',
  },
];
